// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@cogni/ai-tools`
 * Purpose: Barrel export for pure tool definitions and contracts.
 * Scope: Re-exports all public types from submodules. Does NOT import @langchain.
 * Invariants: SINGLE_SOURCE_OF_TRUTH - these are the canonical tool definitions.
 * Side-effects: none
 * Links: LANGGRAPH_AI.md, TOOL_USE_SPEC.md
 * @public
 */

export type {
  AuthCapability,
  ChainDirection,
  ChainNodeEntry,
  CheckInfo,
  CiStatusResult,
  ClockCapability,
  CreateBranchResult,
  DecideParams,
  DispatchCandidateFlightResult,
  EdoCapability,
  EdoSourceType,
  GetChainParams,
  GetChainResult,
  HypothesizeParams,
  KnowledgeCapability,
  KnowledgeEntry,
  KnowledgeListParams,
  KnowledgeSearchParams,
  KnowledgeWriteParams,
  MergeResult,
  MetricDataPoint,
  MetricQueryResult,
  MetricSummary,
  MetricsCapability,
  MetricTemplate,
  MetricWindow,
  PrSummary,
  RecordOutcomeParams,
  RecordOutcomeResult,
  RepoCapability,
  RepoListParams,
  RepoListResult,
  RepoOpenParams,
  RepoOpenResult,
  RepoSearchHit,
  RepoSearchParams,
  RepoSearchResult,
  ScheduleCapability,
  ScheduleCreateParams,
  ScheduleInfo,
  ScheduleUpdateParams,
  TemplateQueryParams,
  ToolCapabilities,
  VcsCapability,
  WebSearchCapability,
  WebSearchParams,
  WebSearchResult,
  // Note: WebSearchResultItem exported from tools/web-search to avoid duplicate
  WebSearchTopic,
  WorkItemAssignee,
  WorkItemCapability,
  WorkItemInfo,
  WorkItemQueryParams,
  WorkItemTransitionResult,
} from "./capabilities";
// Capabilities
export {
  CONFIDENCE,
  createFixedClock,
  makeRepoCitation,
  REPO_CITATION_REGEX,
  stubAuthCapability,
  systemClock,
} from "./capabilities";
// Tool catalog
export {
  type CatalogBoundTool,
  CORE_TOOL_BUNDLE,
  createToolCatalog,
  getToolById,
  getToolIds,
  hasToolId,
  TOOL_CATALOG,
  type ToolCatalog,
} from "./catalog";
// Runtime adapter
export { contractToRuntime, toBoundToolRuntime } from "./runtime-adapter";
// Schema compilation
export {
  type ToToolSpecResult,
  type ToToolSpecsResult,
  toToolSpec,
  toToolSpecs,
} from "./schema";
// Tools
export {
  createEdoDecideImplementation,
  EDO_DECIDE_NAME,
  type EdoDecideDeps,
  type EdoDecideInput,
  EdoDecideInputSchema,
  type EdoDecideOutput,
  EdoDecideOutputSchema,
  type EdoDecideRedacted,
  edoDecideBoundTool,
  edoDecideContract,
  edoDecideStubImplementation,
} from "./tools/edo-decide";
export {
  createEdoHypothesizeImplementation,
  EDO_HYPOTHESIZE_NAME,
  type EdoHypothesizeDeps,
  type EdoHypothesizeInput,
  EdoHypothesizeInputSchema,
  type EdoHypothesizeOutput,
  EdoHypothesizeOutputSchema,
  type EdoHypothesizeRedacted,
  edoHypothesizeBoundTool,
  edoHypothesizeContract,
  edoHypothesizeStubImplementation,
} from "./tools/edo-hypothesize";
export {
  createEdoRecordOutcomeImplementation,
  EDO_RECORD_OUTCOME_NAME,
  type EdoRecordOutcomeDeps,
  type EdoRecordOutcomeInput,
  EdoRecordOutcomeInputSchema,
  type EdoRecordOutcomeOutput,
  EdoRecordOutcomeOutputSchema,
  type EdoRecordOutcomeRedacted,
  edoRecordOutcomeBoundTool,
  edoRecordOutcomeContract,
  edoRecordOutcomeStubImplementation,
} from "./tools/edo-record-outcome";
export {
  GET_CURRENT_TIME_NAME,
  type GetCurrentTimeInput,
  GetCurrentTimeInputSchema,
  type GetCurrentTimeOutput,
  GetCurrentTimeOutputSchema,
  type GetCurrentTimeRedacted,
  getCurrentTimeBoundTool,
  getCurrentTimeContract,
  getCurrentTimeImplementation,
} from "./tools/get-current-time";
export {
  createKnowledgeReadImplementation,
  KNOWLEDGE_READ_NAME,
  type KnowledgeReadDeps,
  type KnowledgeReadInput,
  KnowledgeReadInputSchema,
  type KnowledgeReadOutput,
  KnowledgeReadOutputSchema,
  type KnowledgeReadRedacted,
  knowledgeReadBoundTool,
  knowledgeReadContract,
  knowledgeReadStubImplementation,
} from "./tools/knowledge-read";
export {
  createKnowledgeSearchImplementation,
  KNOWLEDGE_SEARCH_NAME,
  type KnowledgeSearchDeps,
  type KnowledgeSearchInput,
  KnowledgeSearchInputSchema,
  type KnowledgeSearchOutput,
  KnowledgeSearchOutputSchema,
  type KnowledgeSearchRedacted,
  knowledgeSearchBoundTool,
  knowledgeSearchContract,
  knowledgeSearchStubImplementation,
} from "./tools/knowledge-search";
export {
  createKnowledgeWriteImplementation,
  KNOWLEDGE_WRITE_NAME,
  type KnowledgeWriteDeps,
  type KnowledgeWriteInput,
  KnowledgeWriteInputSchema,
  type KnowledgeWriteOutput,
  KnowledgeWriteOutputSchema,
  type KnowledgeWriteRedacted,
  knowledgeWriteBoundTool,
  knowledgeWriteContract,
  knowledgeWriteStubImplementation,
} from "./tools/knowledge-write";
export {
  createMetricsQueryImplementation,
  METRICS_QUERY_NAME,
  type MetricsDataPoint,
  MetricsDataPointSchema,
  type MetricsQueryDeps,
  type MetricsQueryInput,
  MetricsQueryInputSchema,
  type MetricsQueryOutput,
  MetricsQueryOutputSchema,
  type MetricsQueryRedacted,
  type MetricsSummary,
  MetricsSummarySchema,
  metricsQueryBoundTool,
  metricsQueryContract,
  metricsQueryStubImplementation,
} from "./tools/metrics-query";
export {
  createRepoListImplementation,
  REPO_LIST_NAME,
  type RepoListDeps,
  type RepoListInput,
  RepoListInputSchema,
  type RepoListOutput,
  RepoListOutputSchema,
  type RepoListRedacted,
  repoListBoundTool,
  repoListContract,
  repoListStubImplementation,
} from "./tools/repo-list";
export {
  createRepoOpenImplementation,
  REPO_OPEN_NAME,
  type RepoOpenDeps,
  type RepoOpenInput,
  RepoOpenInputSchema,
  type RepoOpenOutput,
  RepoOpenOutputSchema,
  type RepoOpenRedacted,
  repoOpenBoundTool,
  repoOpenContract,
  repoOpenStubImplementation,
} from "./tools/repo-open";
export {
  createRepoSearchImplementation,
  REPO_SEARCH_NAME,
  type RepoSearchDeps,
  type RepoSearchHitOutput,
  RepoSearchHitSchema,
  type RepoSearchInput,
  RepoSearchInputSchema,
  type RepoSearchOutput,
  RepoSearchOutputSchema,
  type RepoSearchRedacted,
  repoSearchBoundTool,
  repoSearchContract,
  repoSearchStubImplementation,
} from "./tools/repo-search";
export {
  createScheduleListImplementation,
  SCHEDULE_LIST_NAME,
  type ScheduleListDeps,
  type ScheduleListInput,
  ScheduleListInputSchema,
  type ScheduleListOutput,
  ScheduleListOutputSchema,
  type ScheduleListRedacted,
  scheduleListBoundTool,
  scheduleListContract,
  scheduleListStubImplementation,
} from "./tools/schedule-list";
export {
  createScheduleManageImplementation,
  SCHEDULE_MANAGE_NAME,
  type ScheduleManageDeps,
  type ScheduleManageInput,
  ScheduleManageInputSchema,
  type ScheduleManageOutput,
  ScheduleManageOutputSchema,
  type ScheduleManageRedacted,
  scheduleManageBoundTool,
  scheduleManageContract,
  scheduleManageStubImplementation,
} from "./tools/schedule-manage";
export {
  createVcsCreateBranchImplementation,
  VCS_CREATE_BRANCH_NAME,
  type VcsCreateBranchDeps,
  type VcsCreateBranchInput,
  VcsCreateBranchInputSchema,
  type VcsCreateBranchOutput,
  VcsCreateBranchOutputSchema,
  type VcsCreateBranchRedacted,
  vcsCreateBranchBoundTool,
  vcsCreateBranchContract,
  vcsCreateBranchStubImplementation,
} from "./tools/vcs-create-branch";
export {
  createVcsFlightCandidateImplementation,
  VCS_FLIGHT_CANDIDATE_NAME,
  type VcsFlightCandidateDeps,
  type VcsFlightCandidateInput,
  VcsFlightCandidateInputSchema,
  type VcsFlightCandidateOutput,
  VcsFlightCandidateOutputSchema,
  type VcsFlightCandidateRedacted,
  vcsFlightCandidateBoundTool,
  vcsFlightCandidateContract,
  vcsFlightCandidateStubImplementation,
} from "./tools/vcs-flight-candidate";
export {
  createVcsGetCiStatusImplementation,
  VCS_GET_CI_STATUS_NAME,
  type VcsGetCiStatusDeps,
  type VcsGetCiStatusInput,
  VcsGetCiStatusInputSchema,
  type VcsGetCiStatusOutput,
  VcsGetCiStatusOutputSchema,
  type VcsGetCiStatusRedacted,
  vcsGetCiStatusBoundTool,
  vcsGetCiStatusContract,
  vcsGetCiStatusStubImplementation,
} from "./tools/vcs-get-ci-status";
export {
  createVcsListPrsImplementation,
  VCS_LIST_PRS_NAME,
  type VcsListPrsDeps,
  type VcsListPrsInput,
  VcsListPrsInputSchema,
  type VcsListPrsOutput,
  VcsListPrsOutputSchema,
  type VcsListPrsRedacted,
  vcsListPrsBoundTool,
  vcsListPrsContract,
  vcsListPrsStubImplementation,
} from "./tools/vcs-list-prs";
export {
  createVcsMergePrImplementation,
  VCS_MERGE_PR_NAME,
  type VcsMergePrDeps,
  type VcsMergePrInput,
  VcsMergePrInputSchema,
  type VcsMergePrOutput,
  VcsMergePrOutputSchema,
  type VcsMergePrRedacted,
  vcsMergePrBoundTool,
  vcsMergePrContract,
  vcsMergePrStubImplementation,
} from "./tools/vcs-merge-pr";
export {
  createWebSearchImplementation,
  WEB_SEARCH_NAME,
  type WebSearchDeps,
  type WebSearchInput,
  WebSearchInputSchema,
  type WebSearchOutput,
  WebSearchOutputSchema,
  type WebSearchRedacted,
  type WebSearchResultItem,
  WebSearchResultItemSchema,
  webSearchBoundTool,
  webSearchContract,
  webSearchStubImplementation,
} from "./tools/web-search";
export {
  createWorkItemQueryImplementation,
  WORK_ITEM_QUERY_NAME,
  type WorkItemQueryDeps,
  type WorkItemQueryInput,
  WorkItemQueryInputSchema,
  type WorkItemQueryOutput,
  WorkItemQueryOutputSchema,
  type WorkItemQueryRedacted,
  workItemQueryBoundTool,
  workItemQueryContract,
  workItemQueryStubImplementation,
} from "./tools/work-item-query";
export {
  createWorkItemTransitionImplementation,
  WORK_ITEM_TRANSITION_NAME,
  type WorkItemTransitionDeps,
  type WorkItemTransitionInput,
  WorkItemTransitionInputSchema,
  type WorkItemTransitionOutput,
  WorkItemTransitionOutputSchema,
  type WorkItemTransitionRedacted,
  workItemTransitionBoundTool,
  workItemTransitionContract,
  workItemTransitionStubImplementation,
} from "./tools/work-item-transition";
// Tool types
export type {
  BoundTool,
  ToolContract,
  ToolErrorCode,
  ToolImplementation,
  ToolResult,
} from "./types";
